/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package medicosmodule.vistas;

import medicosmodule.conexion.ConectorDB;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author jotab
 */
public class RegistrarVacacion extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarVacacion
     */
    public RegistrarVacacion() {
        initComponents();
        cargarMedicosEnCombo();
        btnRegistrarVacaciones.addActionListener(e -> registrarVacaciones());
    }
    
    private void cargarMedicosEnCombo() {
        cmbMedicoVacaciones.removeAllItems();
        try (Connection conn = ConectorDB.conectar(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery("SELECT Nombre, Apellido FROM Medicos")) {
            while (rs.next()) {
                String nombreCompleto = rs.getString("Nombre") + " " + rs.getString("Apellido");
                cmbMedicoVacaciones.addItem(nombreCompleto);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar médicos en combo: " + ex.getMessage());
        }
    }
    private void registrarVacaciones() {
        String medicoSeleccionado = (String) cmbMedicoVacaciones.getSelectedItem();
        LocalDate desde = pickerDesde.getDate();
        LocalDate hasta = pickerHasta.getDate();
        LocalDate hoy = LocalDate.now();
        if (desde.isBefore(hoy)) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio debe ser igual o posterior a hoy.");
            return;
        }

        if (medicoSeleccionado == null || desde == null || hasta == null) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos para registrar vacaciones.");
            return;
        }

        if (desde.isAfter(hasta)) {
            JOptionPane.showMessageDialog(this, "La fecha 'desde' no puede ser posterior a la fecha 'hasta'.");
            return;
        }

        try (Connection conn = ConectorDB.conectar(); PreparedStatement ps = conn.prepareStatement("INSERT INTO EstadoMedico (IdMedico, FechaDesde, FechaHasta, Estado) VALUES ((SELECT IdMedico FROM Medicos WHERE CONCAT(Nombre, ' ', Apellido) = ?), ?, ?, 'Vacaciones')")) {
            ps.setString(1, medicoSeleccionado);
            ps.setDate(2, Date.valueOf(desde));
            ps.setDate(3, Date.valueOf(hasta));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Vacaciones registradas correctamente.");
            pickerDesde.clear();
            pickerHasta.clear();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al registrar vacaciones: " + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbMedicoVacaciones = new javax.swing.JComboBox<>();
        pickerDesde = new com.github.lgooddatepicker.components.DatePicker();
        pickerHasta = new com.github.lgooddatepicker.components.DatePicker();
        btnRegistrarVacaciones = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 238, 252));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Registrar Vacaciones");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel8.setText("Seleccione el médico ");

        cmbMedicoVacaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegistrarVacaciones.setBackground(new java.awt.Color(0, 51, 255));
        btnRegistrarVacaciones.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        btnRegistrarVacaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarVacaciones.setText("Registrar Vacaciones");

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel10.setText("Desde:");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel9.setText("Hasta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMedicoVacaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pickerHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(pickerDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnRegistrarVacaciones)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbMedicoVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pickerDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pickerHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarVacaciones)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarVacaciones;
    private javax.swing.JComboBox<String> cmbMedicoVacaciones;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.github.lgooddatepicker.components.DatePicker pickerDesde;
    private com.github.lgooddatepicker.components.DatePicker pickerHasta;
    // End of variables declaration//GEN-END:variables
}
