/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import static java.time.Clock.system;
import static java.time.InstantSource.system;
import pacientesmodule.vista.informacion_doctor;
import pacientesmodule.vista.informacion_paciente;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import pacientesmodule.conexion.ConexionSQLServer;
import pacientesmodule.vista.informacion_enfermero;
/**
 *
 * @author USUARIO
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlusuario = new javax.swing.JLabel();
        jtfusuario = new javax.swing.JTextField();
        jlcontrasena = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jAceptar = new javax.swing.JButton();
        jpfcontrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlusuario.setText("Usuario");

        jlcontrasena.setText("Contraseña");

        jButton1.setText("Salir ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jAceptar.setText("Ingresar");
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAceptar)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlcontrasena)
                    .addComponent(jlusuario))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpfcontrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jtfusuario))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlusuario)
                    .addComponent(jtfusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlcontrasena)
                    .addComponent(jpfcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jAceptar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
        String usuario = this.jtfusuario.getText().trim();
    char[] passwordChars = jpfcontrasena.getPassword();
    String contrasena = new String(passwordChars).trim();
    
    // Limpiar array de contraseña por seguridad
    java.util.Arrays.fill(passwordChars, ' ');
    
    try (Connection conn = ConexionSQLServer.conectar()) {
        // Buscar en Enfermeros
String enfermeroQuery = "SELECT cedula, contrasena_enfermero, nombres, apellidos FROM Enfermero WHERE cedula = ?";
try (PreparedStatement stmt = conn.prepareStatement(enfermeroQuery)) {
    stmt.setString(1, usuario);
    ResultSet rs = stmt.executeQuery();
    
    if (rs.next()) {
        String dbPassword = rs.getString("contrasena_enfermero");
        if (dbPassword != null && dbPassword.equals(contrasena)) {
            String cedulaEnfermero = rs.getString("cedula");
            String nombres = rs.getString("nombres");
            String apellidos = rs.getString("apellidos");
            
            JOptionPane.showMessageDialog(this, 
                "Acceso concedido como enfermero ",
                "Autenticación exitosa", 
                JOptionPane.INFORMATION_MESSAGE);
            
            informacion_enfermero enfermeroView = new informacion_enfermero(cedulaEnfermero);
            enfermeroView.setVisible(true);
            this.dispose(); // Cerrar ventana de login
            return;
        }
    }
}
        // Buscar en Pacientes
        String pacienteQuery = "SELECT cedula, contrasena_paciente FROM Paciente WHERE cedula = ?";
        try (PreparedStatement stmt = conn.prepareStatement(pacienteQuery)) {
            stmt.setString(1, usuario);
            ResultSet rs = stmt.executeQuery();
            
            if (rs.next()) {
                String dbPassword = rs.getString("contrasena_paciente");
                String cedula= rs.getString("cedula");
                if (dbPassword != null && dbPassword.equals(contrasena)) {
                    JOptionPane.showMessageDialog(this, "Acceso concedido como paciente");
                    informacion_paciente paciente = new informacion_paciente(cedula);
                    paciente.setVisible(true);
                    this.dispose(); // Cerrar ventana de login
                    return;
                }
            }
        }
        
        // Buscar en Doctores
        String doctorQuery = "SELECT cedula, contrasena_doctor FROM Doctor WHERE cedula = ?";
        try (PreparedStatement stmt = conn.prepareStatement(doctorQuery)) {
            stmt.setString(1, usuario);
            ResultSet rs = stmt.executeQuery();
            
            if (rs.next()) {
                String dbPassword = rs.getString("contrasena_doctor");
                if (dbPassword != null && dbPassword.equals(contrasena)) {
                    String cedulaDoctor = rs.getString("cedula");
                    JOptionPane.showMessageDialog(this, "Acceso concedido como Médico");
                    informacion_doctor doctor = new informacion_doctor(cedulaDoctor);
                    doctor.setVisible(true);
                    this.dispose(); // Cerrar ventana de login
                    return;
                }
            }
        }
        
        
        
        // Si no coincide en ninguna tabla
        JOptionPane.showMessageDialog(this, 
            "Usuario o contraseña incorrectos", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        this.jtfusuario.setText("");
        this.jpfcontrasena.setText("");
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Error de conexión: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }     
        
    }//GEN-LAST:event_jAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jlcontrasena;
    private javax.swing.JLabel jlusuario;
    private javax.swing.JPasswordField jpfcontrasena;
    private javax.swing.JTextField jtfusuario;
    // End of variables declaration//GEN-END:variables
}
